server:
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test?currentSchema=test
    username: postgres
    password: admin
  liquibase:
    enabled: true
    change-log: classpath:database-changelog.xml
    url: jdbc:postgresql://localhost:5432/test?currentSchema=test
    user: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    open-in-view: false

